/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_sispop_sispopnet_SispopnetVPN_VPNInfo */

#ifndef _Included_network_sispop_sispopnet_SispopnetVPN_VPNInfo
#define _Included_network_sispop_sispopnet_SispopnetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
