/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_sispop_sispopnet_SispopnetConfig */

#ifndef _Included_network_sispop_sispopnet_SispopnetConfig
#define _Included_network_sispop_sispopnet_SispopnetConfig
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_sispop_sispopnet_SispopnetConfig
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_sispop_sispopnet_SispopnetConfig_Obtain(JNIEnv *, jclass);

  /*
   * Class:     network_sispop_sispopnet_SispopnetConfig
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_sispop_sispopnet_SispopnetConfig_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetConfig
   * Method:    Load
   * Signature: (Ljava/lang/String;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetConfig_Load(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
