/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_sispop_sispopnet_SispopnetDaemon */

#ifndef _Included_network_sispop_sispopnet_SispopnetDaemon
#define _Included_network_sispop_sispopnet_SispopnetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_Obtain(JNIEnv *, jclass);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    Configure
   * Signature: (Lnetwork/sispop/sispopnet/SispopnetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_Configure(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_Mainloop(JNIEnv *, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_IsRunning(JNIEnv *, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetDaemon
   * Method:    InjectVPN
   * Signature: (Lnetwork/sispop/sispopnet/SispopnetVPN;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetDaemon_InjectVPN(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
