/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_sispop_sispopnet_SispopnetVPN */

#ifndef _Included_network_sispop_sispopnet_SispopnetVPN
#define _Included_network_sispop_sispopnet_SispopnetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_PacketSize(JNIEnv *, jclass);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_Alloc(JNIEnv *, jclass);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_ReadPkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_WritePkt(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_sispop_sispopnet_SispopnetVPN
   * Method:    SetInfo
   * Signature: (Lnetwork/sispop/sispopnet/SispopnetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_network_sispop_sispopnet_SispopnetVPN_SetInfo(JNIEnv *, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
