#!/bin/sh
echo "Running preinstall" > /tmp/sispopnet_preinstall.log
if [ ! -d "$HOME/.sispopnet" ]
then
  mkdir $HOME/.sispopnet >> /tmp/sispopnet_preinstall.log
fi
find $HOME/.sispopnet >> /tmp/sispopnet_preinstall.log
exit 0 # all good
