#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/sispopnet || echo "failed to setcap sispopnet"
adduser --quiet --system --home /var/lib/sispopnet debian-sispopnet || echo "debian-sispopnet user not added"
